### ISSUE TITLE
problem compiling code

### ISSUE THREAD

**Issue by tommybotch** [Telecommunication-Telemedia-Assessment/GBVS360-BMS360-ProSal#2]
Hey,

Thank you for making the GBVS360 code publicly available. I have a question about compiling that I'm wondering if you could help me with. I'm wondering if my path structure is correct.

I unzipped the library folder from the link provided and placed it at the same level of my directory hierarchy as the cloned GBVS360 folder. Specifically, my directory structure looks like this: 

C:\Users\Robertson Lab\Desktop\Salience\GBVS360-BMS360-ProSal-master
C:\Users\Robertson Lab\Desktop\Salience\Library

When I load the solution file "Salient360.sln" in Visual Studio Community 2015 and attempt to compile, I receive multiple of the following errors (pasted below). Do you have any advice for compiling the code from here?

![image](https://user-images.githubusercontent.com/42591108/47021909-6c439480-d12a-11e8-9b53-62d392fe433f.png)

Thank you for your help in advance!

**Comment by plebreton** [comment]
Hello,

OK, you can try to get the code again. Your setup is correct, it is just that the path were changed in the VS project because I was using more recent version of the depending libraries. I switched them back to be consistent with the library folder hosted on onedrive, so now you should be able to compile the project .

**Comment by tommybotch** [comment]
Hi,

Thank you for your reply and the help. The code now compiles successfully - we are very appreciative of your assistance!
