### ISSUE TITLE
gnomonic command line interface

### ISSUE THREAD

**Issue by tommybotch** [Telecommunication-Telemedia-Assessment/GBVS360-BMS360-ProSal#4]
Hello,

Thank you again for your help with the GBVS360 libraries! I am currently trying to access the functionality of the gnomonic dir. I am using VirtualBox Ubuntu 16.04 LTS. Here is a picture of my path as well as the "make" inside the dir.

<img width="730" alt="screen shot 2018-11-09 at 12 57 20 pm" src="https://user-images.githubusercontent.com/42591108/48279652-38a11500-e41f-11e8-812c-14f2bc58055f.png">

I was wondering if you could provide guidance to building this interface (I assume it can be used to get rectilinear projects from equirectangular maps).

Thank you in advance!

**Comment by plebreton** [comment]
Hello,

Here you just need to install clang++ as I use this compiler instead of g++.
`apt-get install clang++`

Make sure that you also have boost and opencv installed as this project depends on it.
`apt-get install libboost-all-dev libopencv-dev`

And you should better compile it from the root folder of the project `~/GBVS360-BMS360-ProSal/ `. Run make from there, and you should find the binary in the `gnomonic/bin` folder.
